### ISSUE TITLE
Some plugins insert dependencies not on the file system

### ISSUE THREAD

**Issue by cognitom** [suluke/express-middleware-rollup#7]
`rollup-plugin-commonjs` inserts a helper dependency `\u0000commonjsHelpers`.
I think we need to filter such id which has no valid paths.

- usual dependencies: `{ id: '/path/to/marked/lib/marked.js' }`
- inserted dependencies: `{ id: '\u0000commonjsHelpers' }`

At this point, the quick fix could be like this around [this line](https://github.com/suluke/express-middleware-rollup/blob/v1.0.1/index.js#L245):

```javascript
const dependencies = bundle.modules
  .map(module => module.id)
  .filter(id => id[0] !== '\u0000');
```

**Comment by suluke** [comment]
This sounds indeed like a serious issue. I will investigate whether these pseudo-paths are explicitly part of the rollup system

**Comment by suluke** [comment]
I think your idea involving `filter` is a little too superficial in general. The most robust solution would be to test all the dependencies we got from the rollup bundle if they actually exist - but only AFTER a *successful* compilation, because failing bundle compilations might be due to a non-existing file. This is how we can make sure that we only consider *real* file dependencies. One problem with this is that we would always rebuild the bundle on the first load when the dependency cache is still empty (because there hasn't been a successful build yet). We can add a heuristic here to improve this, though, similar to what you have suggested: `.filter(id => isValidFileName(id))`, where `isValidFileName` can be arbitrarily complex.
All these considerations aside: The current implementation of `allFilesOlder` definitely needs to be more robust. We never check if a file exists, only its modification time.

**Comment by cognitom** [comment]
Agreed. `isValidFileName(id)` looks reasonable. We could elaborate it in the future, if needed.

I've found [path.isAbsolute()](https://nodejs.org/api/path.html#path_path_isabsolute_path) is also useful for this purpose.

```javascript
const isValidFileName = id => path.isAbsolute(id);
const dependencies = bundle.modules
  .map(module => module.id)
  .filter(id => isValidFileName(id));
```
